application:
  name: forage-midas-flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port:
    33400

general:
  kafka-topic: transactions

spring:
  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  kafka:
    consumer:
      boostrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        .spring:
          json:
            trusted:
              packages: '*'
    producer:
      boostrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer